const ADD_CART = "ADD_CART";
const HANDEL_DELETE = "HANDEL_DELETE";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const CLEAR_CART = "CLEAR_CART";
const DETAILSPRODUCT = "DETAILSPRODUCT";

export {
  ADD_CART,
  HANDEL_DELETE,
  INCREMENT,
  DECREMENT,
  CLEAR_CART,
  DETAILSPRODUCT,
};
